### PR TITLE
Made sure warnings line up horizontally with their elements

### PR DESCRIPTION
**Pull request by mmcev106**
A good example of a scenario where this did not occur previously is when multiple validated elements are on the same line.

### CODE REVIEW

**Comment by farneman** [comment]
I certainly see how this is an issue but personally I feel like this problem is a CSS issue that should be addressed by individual implementors. Injecting inline CSS at the library level makes it much more difficult to override the style if you want to do something different.

**Comment by mmcev106** [comment]
I'd love it if we could find a good way to make Hyperform smart enough to line up warnings horizontally out of the box in this case.  Can you think of any alternate strategies to make this happen that you'd be comfortable with?  If so, I'd be happy to implement them to solve this for everyone.  Let me know if you want to make a jsfiddle to demonstrate the issue.

**Comment by farneman** [comment]
If we could find a way to do so purely in CSS and include it in the supplied `hyperform.css` file that would be fine. In most cases (except maybe completely unstyled form elements) inputs that are lined up horizontally have been done so by the projects authors via CSS therefore I don't think it's too much too ask for them to style accordingly.

Also, I'm not sure a left margin alone would be sufficient to line up the message and input in all cases depending on the context. Do you have an example of the context you're using it in for reference?

**Comment by mmcev106** [comment]
[Click here](https://jsfiddle.net/p5w4wa84/6/) for a basic example of the scenario I was trying prevent.  I'm not aware of any pure CSS solutions, but I'd be happy to implement one if you have any ideas.  I later realized a reasonable workaround was simply to wrap each input in a div, so I'll keep that mind going forward.

**Comment by farneman** [comment]
Yeah, that's a good work around.

In my opinion, having inputs inline without any wrapping elements seems like a pretty specific use case. I wish there was a way to handle it out of the box but I'm not aware of any way to accomplish it via CSS either. 

I think applying an inline `margin-left` style via JavaScript all the time is too heavy-handed a solution. It's more likely to cause styling or display problems for other more common uses.

**Pull request closed without merging**
